config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  devise_for :users 
  devise_scope :user do
  authenticated :user do
    root 'home#index', as: :authenticated_root
  end

  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end
  resources :products
  resources :categories
  
 root :to => "devise/sessions#new"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :product
    accepts_nested_attributes_for :product
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

    def after_sign_out_path_for(resource_or_scope)
      root_path
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'A categoria foi criada com sucesso.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: '
        A categoria foi atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: '
      A categoria foi excluida com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: '
        O produto foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'O produto foi atualizado com sucesso
        .' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'O produto foi excluido com sucesso
      .' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :amount, :value,{:categories_attributes => [:name]})
      
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-group row">
        <%= form.label :name, "Nome", class: "col-sm-1 control-label" %>
        <div class="col-md-6">
          <%= form.text_field :name, id: :category_name, class: "form-control" %>
        </div>
      </div>

  <div class="actions">
    <%= form.submit 'Criar Categoria', class: 'btn btn-primary'%>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editar categoria</h1>

<%= render 'form', category: @category %>

<%= link_to 'Lista', @category %> |
<%= link_to 'Voltar', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categorias</h1>

<table class="table">
  <thead "thead-default">
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        
        <td><%= link_to 'Editar', edit_category_path(category), class: 'glyphicon glyphicon-pencil' %></td>
        <td><%= link_to 'Exluir', category, method: :delete, data: { confirm: 'Você tem certeza?' }, class: "glyphicon glyphicon-trash"  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova Categoria', new_category_path, class: 'btn btn-primary' %>

app/views/categories/new.html.erb
<h1>Nova categoria</h1>

<%= render 'form', category: @category %>
<%= link_to 'Voltar', categories_path, class: 'btn btn-primary' %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Editar', edit_category_path(@category), class: 'btn btn-primary' %> |
<%= link_to 'Voltar', categories_path, class: 'btn btn-primary'%>

app/views/home/index.html.erb
          <div class="row col-xs-12 col-sm-12 col-md-12 col-lg-12"  align="center">
                
<h1>Bem Vindo</h1><br/>
<h1>ao seu Gerenciador</h1><br/>
<h1>de Estoques</h1>
            </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

  <style type="text/css">
  .nav-link{
    color: #fff;
}
.btn btn-inverse {
    color: #fff;
}
.navbar-brand{
    color: #fff;
}
  </style>

    <title>SimpleStock</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">
    
  </head>

  <body>
 
 


 <nav class="navbar navbar-custom" style="background-color: #1874CD; border-color: #000;" >
  <div class="container">
    <%= link_to home_index_path do %>
  <%= content_tag :span, "Simple Stock", :class => "navbar-brand d-flex w-60 mr-auto" %>
<% end %>
   
   
        <ul class="nav navbar-nav">
            <li class="nav-item active" >
                <%= link_to "Categoria", categories_path, :class => "nav-link" %> 
            </li>
           
            <li class="nav-item active">
                <%= link_to "Estoque", products_path, :class => "nav-link" %> 
            </li>
        </ul>
         <ul class="nav navbar-nav navbar-right">
            <li class="nav-item active">
               <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, :class => "nav-link" %>
            </li>
    </div>
</nav>

    
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   <div class="form-group row">
        <%= form.label :name, class: "col-sm-1 control-label" %>
        <div class="col-md-4">
          <%= form.text_field :name, id: :product_name, class: "form-control" %>
        </div>
   </div>
  
   <div class="form-group row">
        <%= form.label :description, class: "col-sm-1 control-label" %>
        <div class="col-md-4">
          <%= form.text_field :description, id: :product_description, class: "form-control" %>
        </div>
   </div>
  
  <div class="form-group row">
        <%= form.label :amount, class: "col-sm-1 control-label" %>
        <div class="col-md-4">
          <%= form.text_field :amount, id: :product_amount, class: "form-control" %>
        </div>
   </div>

     <div class="form-group row">
        <%= form.label :value, class: "col-sm-1 control-label" %>
        <div class="col-md-4">
          <%= form.text_field :value, id: :product_value, class: "form-control" %>
        </div>
   </div>



  <div class="form-group row">
    <%= form.label :category_id, class: "col-sm-1 control-label" %> 

    <%= select("post", "category", Category.all.collect {|p| [ p.name, p.id ] }, { include_blank: true })%>
    <%= select "get", "category", Category.all.collect {|x| [x.name, x.id]} %>
  </div>

  <div class="actions">
    <%= form.submit 'Criar Produto', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editar Produto</h1>

<%= render 'form', product: @product %>


<%= link_to 'Voltar', products_path, class: 'btn btn-primary' %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Produtos</h1>

<table class="table">
  <thead class="thead-default">
    <tr>
      <th>Nome</th>
      <th>Descrição</th>
      <th>Quantidade</th>
      <th>Valor</th>
      <th>Categoria</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.amount %></td>
        <td><%= product.value %></td>
        <td><%= product.category_id %></td>
       
        <td><%= link_to 'Editar', edit_product_path(product), class: 'glyphicon glyphicon-pencil' %></td>
        <td><%= link_to 'Excluir', product, method: :delete, data: { confirm: 'Você tem certeza?' }, class: "glyphicon glyphicon-trash" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Produto', new_product_path, class: 'btn btn-primary' %>

app/views/products/new.html.erb
<h1>Novo Produto</h1>

<%= render 'form', product: @product %>

<%= link_to 'Voltar', products_path, class: 'btn btn-primary' %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @product.amount %>
</p>

<p>
  <strong>Value:</strong>
  <%= @product.value %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @product.category_id %>
</p>
<%= link_to 'Editar', edit_product_path(@product), class: 'btn btn-primary' %> |
<%= link_to 'Voltar', products_path, class: 'btn btn-primary' %>